name: Github Page Publish
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'test/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup Node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
          npm run predoc
          npm run build:docs

      - name: Github REST API Call 🛎️
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PARENT_REPO: yorkie-team/yorkie-team.github.io
          PARENT_BRANCH: main
          WORKFLOW_ID: <9999999>
        run: |
        curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.GITHUB_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
where
